export const PROGRAM = {
  name: 'Spring 2026',
  sessionTypes: {
    'lower-a': {
      name: 'Lower A',
      day: 'Monday',
      focus: 'Strength + Hypertrophy',
      exercises: [
        { slotId: 'la-squat',     name: 'Barbell Back Squat', sets: 0, repRange: null, rir: null, rest: '3–4 min', is531: true, note: '5s PRO — track manually' },
        { slotId: 'la-legpress',  name: 'Leg Press', sets: 3, repRange: [10, 12], rir: 2, rest: '90 sec', subs: [{ name: 'Bulgarian Split Squat', sets: 2, repRange: [8, 8], rir: 2, perSide: true }, 'Goblet Squat'] },
        { slotId: 'la-rdl',       name: 'Romanian Deadlift', sets: 3, repRange: [6, 10], rir: 2, rest: '2 min', subs: ['DB Romanian Deadlift', 'KB Romanian Deadlift'] },
        { slotId: 'la-hipthrust', name: 'Barbell Hip Thrust', sets: 2, repRange: [8, 12], rir: 2, rest: '90 sec', subs: ['DB Hip Thrust', 'KB Hip Thrust', 'Cable Hip Thrust'] },
        { slotId: 'la-calf',      name: 'Standing Calf Raise', sets: 3, repRange: [15, 20], rir: 1, rest: '60 sec', subs: ['Single-Leg DB Calf Raise', 'Standing Calf Raise Machine'] },
      ],
    },
    'upper-a': {
      name: 'Upper A',
      day: 'Tuesday',
      focus: 'Strength + Hypertrophy',
      exercises: [
        { slotId: 'ua-bench',   name: 'Flat Barbell Bench Press', sets: 0, repRange: null, rir: null, rest: '3–4 min', is531: true, note: '5s PRO — track manually' },
        { slotId: 'ua-pullup',  name: 'Weighted Pull-Up', sets: 4, repRange: [6, 10], rir: 2, rest: '90 sec', subs: ['Lat Pulldown', 'Band-Assisted Pull-Up', 'Pull-Up'] },
        { slotId: 'ua-row',     name: 'Seated Cable Row', sets: 3, repRange: [8, 12], rir: 2, rest: '90 sec', subs: ['Barbell Bent-Over Row', 'DB Bent-Over Row'] },
        { slotId: 'ua-press',   name: 'Seated DB Shoulder Press', sets: 3, repRange: [8, 12], rir: 2, rest: '90 sec', subs: ['Standing DB Shoulder Press', 'Machine Shoulder Press'] },
        { slotId: 'ua-lateral', name: 'Cable Lateral Raise', sets: 4, repRange: [12, 15], rir: 1, rest: '60 sec', subs: ['DB Lateral Raise', 'Incline Dumbbell Y Raise', 'Machine Lateral Raise'] },
        { slotId: 'ua-fly',     name: 'Incline Cable Fly', sets: 2, repRange: [10, 12], rir: 1, rest: '60 sec', subs: ['Incline DB Fly', 'Pec Deck', 'Flat Cable Fly', 'Decline Cable Fly'] },
        { slotId: 'ua-tri',     name: 'Tricep Bar Pushdown', sets: 4, repRange: [10, 12], rir: 1, rest: '60 sec', superset: 'A', subs: ['Tricep Rope Pushdown', 'Band Tricep Pushdown'] },
        { slotId: 'ua-curl',    name: 'EZ Bar Curl', sets: 4, repRange: [10, 12], rir: 1, rest: '60 sec', superset: 'A', subs: ['DB Curl', 'Barbell Curl', 'Bicep Curl Machine', 'DB Preacher Curl', 'EZ Preacher Curl'] },
      ],
    },
    'lower-b': {
      name: 'Lower B',
      day: 'Thursday',
      focus: 'Hypertrophy',
      exercises: [
        { slotId: 'lb-squat',   name: 'Pendulum Squat', sets: 3, repRange: [8, 12], rir: 2, rest: '2 min', subs: ['Hack Squat', 'Front Squat', 'Goblet Squat', 'V-Squat'] },
        { slotId: 'lb-legcurl', name: 'Seated Leg Curl', sets: 3, repRange: [10, 12], rir: 1, rest: '90 sec', subs: [{ name: 'Nordic Curl', sets: 2, repRange: [5, 8], rir: 2 }, { name: 'Glute Ham Raise', sets: 2, repRange: [5, 8], rir: 2 }, 'Lying Leg Curl'] },
        { slotId: 'lb-rdl',     name: 'Single-Leg Romanian Deadlift', sets: 2, repRange: [8, 10], rir: 2, rest: '90 sec', perSide: true, subs: ['DB Single-Leg RDL', 'KB Single-Leg RDL'] },
        { slotId: 'lb-legext',  name: 'Leg Extension', sets: 3, repRange: [10, 12], rir: 1, rest: '60 sec', superset: 'A', subs: ['Cable Leg Extension'] },
        { slotId: 'lb-calf',    name: 'Seated Calf Raise', sets: 3, repRange: [15, 20], rir: 1, rest: '60 sec', superset: 'A', subs: ['Seated DB Calf Raise'] },
      ],
    },
    'upper-b': {
      name: 'Upper B',
      day: 'Friday',
      focus: 'Hypertrophy',
      exercises: [
        { slotId: 'ub-press',    name: 'Incline DB Press', sets: 4, repRange: [8, 12], rir: 2, rest: '90 sec', subs: ['Incline Barbell Press', 'Machine Incline Press'] },
        { slotId: 'ub-pullup',   name: 'Pull-Up', sets: 3, repRange: [8, 12], rir: 2, rest: '90 sec', subs: ['Lat Pulldown', 'Band-Assisted Pull-Up'] },
        { slotId: 'ub-row',      name: 'Chest-Supported DB Row', sets: 3, repRange: [10, 12], rir: 2, rest: '90 sec', subs: ['Single-Arm DB Row', 'Machine Row', 'Machine Chest-Supported Row'] },
        { slotId: 'ub-fly',      name: 'Incline Cable Fly', sets: 3, repRange: [10, 12], rir: 1, rest: '60 sec', subs: ['Incline DB Fly', 'Pec Deck', 'Flat Cable Fly', 'Decline Cable Fly'] },
        { slotId: 'ub-facepull', name: 'Cable Face Pull', sets: 3, repRange: [12, 15], rir: 1, rest: '60 sec', superset: 'A', subs: ['Rear Delt Fly', 'Reverse Cable Crossover', 'Lying DB Reverse Fly'] },
        { slotId: 'ub-lateral',  name: 'Cable Lateral Raise', sets: 4, repRange: [12, 15], rir: 1, rest: '60 sec', superset: 'A', subs: ['DB Lateral Raise', 'Incline Dumbbell Y Raise', 'Machine Lateral Raise'] },
        { slotId: 'ub-tri',      name: 'Cable Overhead Tricep Extension', sets: 2, repRange: [10, 12], rir: 1, rest: '60 sec', superset: 'B', subs: ['DB Overhead Tricep Extension'] },
        { slotId: 'ub-curl',     name: 'Hammer Curl', sets: 3, repRange: [10, 12], rir: 1, rest: '60 sec', superset: 'B', subs: ['Cross-Body Hammer Curl'] },
      ],
    },
    'upper-c': {
      name: 'Upper C',
      day: 'Sunday',
      focus: 'Arms + Delts',
      exercises: [
        { slotId: 'uc-pulldown', name: 'Lat Pulldown', sets: 3, repRange: [8, 12], rir: 2, rest: '90 sec' },
        { slotId: 'uc-lateral',  name: 'Cable Lateral Raise', sets: 3, repRange: [12, 15], rir: 1, rest: '60 sec', superset: 'A', subs: ['DB Lateral Raise', 'Incline Dumbbell Y Raise', 'Machine Lateral Raise'] },
        { slotId: 'uc-facepull', name: 'Cable Face Pull', sets: 3, repRange: [12, 15], rir: 1, rest: '60 sec', superset: 'A', subs: ['Rear Delt Fly', 'Reverse Cable Crossover', 'Lying DB Reverse Fly'] },
        { slotId: 'uc-tri',      name: 'Tricep Bar Pushdown', sets: 3, repRange: [10, 12], rir: 1, rest: '60 sec', superset: 'B', subs: ['Tricep Rope Pushdown', 'Band Tricep Pushdown'] },
        { slotId: 'uc-curl',     name: 'Incline DB Curl', sets: 3, repRange: [10, 12], rir: 1, rest: '60 sec', superset: 'B' },
        { slotId: 'uc-oht',      name: 'Cable Overhead Tricep Extension', sets: 2, repRange: [10, 12], rir: 1, rest: '60 sec', superset: 'C', subs: ['DB Overhead Tricep Extension'] },
        { slotId: 'uc-hammer',   name: 'Hammer Curl', sets: 2, repRange: [10, 12], rir: 1, rest: '60 sec', superset: 'C', subs: ['Cross-Body Hammer Curl'] },
      ],
    },
    'upper-a-5': {
      name: 'Upper A-5',
      day: 'Tuesday',
      focus: 'Strength + Hypertrophy (5-day)',
      exercises: [
        { slotId: 'ua-bench',   name: 'Flat Barbell Bench Press', sets: 0, repRange: null, rir: null, rest: '3–4 min', is531: true, note: '5s PRO — track manually' },
        { slotId: 'ua-pullup',  name: 'Weighted Pull-Up', sets: 4, repRange: [6, 10], rir: 2, rest: '90 sec', subs: ['Lat Pulldown', 'Band-Assisted Pull-Up', 'Pull-Up'] },
        { slotId: 'ua-row',     name: 'Seated Cable Row', sets: 3, repRange: [8, 12], rir: 2, rest: '90 sec', subs: ['Barbell Bent-Over Row', 'DB Bent-Over Row'] },
        { slotId: 'ua-press',   name: 'Seated DB Shoulder Press', sets: 3, repRange: [8, 12], rir: 2, rest: '90 sec', subs: ['Standing DB Shoulder Press', 'Machine Shoulder Press'] },
        { slotId: 'ua-lateral', name: 'Cable Lateral Raise', sets: 4, repRange: [12, 15], rir: 1, rest: '60 sec', subs: ['DB Lateral Raise', 'Incline Dumbbell Y Raise', 'Machine Lateral Raise'] },
        { slotId: 'ua-fly',     name: 'Incline Cable Fly', sets: 2, repRange: [10, 12], rir: 1, rest: '60 sec', subs: ['Incline DB Fly', 'Pec Deck', 'Flat Cable Fly', 'Decline Cable Fly'] },
        { slotId: 'ua-tri',     name: 'Tricep Bar Pushdown', sets: 3, repRange: [10, 12], rir: 1, rest: '60 sec', superset: 'A', subs: ['Tricep Rope Pushdown', 'Band Tricep Pushdown'] },
        { slotId: 'ua-curl',    name: 'EZ Bar Curl', sets: 3, repRange: [10, 12], rir: 1, rest: '60 sec', superset: 'A', subs: ['DB Curl', 'Barbell Curl', 'Bicep Curl Machine', 'DB Preacher Curl', 'EZ Preacher Curl'] },
      ],
    },
    'upper-b-5': {
      name: 'Upper B-5',
      day: 'Friday',
      focus: 'Hypertrophy (5-day)',
      exercises: [
        { slotId: 'ub-press',    name: 'Incline DB Press', sets: 4, repRange: [8, 12], rir: 2, rest: '90 sec', subs: ['Incline Barbell Press', 'Machine Incline Press'] },
        { slotId: 'ub-pullup',   name: 'Pull-Up', sets: 3, repRange: [8, 12], rir: 2, rest: '90 sec', subs: ['Lat Pulldown', 'Band-Assisted Pull-Up'] },
        { slotId: 'ub-row',      name: 'Chest-Supported DB Row', sets: 3, repRange: [10, 12], rir: 2, rest: '90 sec', subs: ['Single-Arm DB Row', 'Machine Row', 'Machine Chest-Supported Row'] },
        { slotId: 'ub-fly',      name: 'Incline Cable Fly', sets: 3, repRange: [10, 12], rir: 1, rest: '60 sec', subs: ['Incline DB Fly', 'Pec Deck', 'Flat Cable Fly', 'Decline Cable Fly'] },
        { slotId: 'ub-facepull', name: 'Cable Face Pull', sets: 3, repRange: [12, 15], rir: 1, rest: '60 sec', superset: 'A', subs: ['Rear Delt Fly', 'Reverse Cable Crossover', 'Lying DB Reverse Fly'] },
        { slotId: 'ub-lateral',  name: 'Cable Lateral Raise', sets: 3, repRange: [12, 15], rir: 1, rest: '60 sec', superset: 'A', subs: ['DB Lateral Raise', 'Incline Dumbbell Y Raise', 'Machine Lateral Raise'] },
        { slotId: 'ub-tri',      name: 'Cable Overhead Tricep Extension', sets: 2, repRange: [10, 12], rir: 1, rest: '60 sec', superset: 'B', subs: ['DB Overhead Tricep Extension'] },
        { slotId: 'ub-curl',     name: 'Hammer Curl', sets: 2, repRange: [10, 12], rir: 1, rest: '60 sec', superset: 'B', subs: ['Cross-Body Hammer Curl'] },
      ],
    },
  },
}
